packages:
- '.'
resolver: ghc-7.8
flags:
  text:
    integer-simple: false
  curl:
    new-base: true
extra-deps:
- BoundedChan-1.0.3.0
- MonadRandom-0.4
- attoparsec-0.13.0.1
- blaze-builder-0.4.0.1
- bson-0.3.1
- byteable-0.1.1
- bytestring-lexing-0.5.0.2
- case-insensitive-1.2.0.4
- cryptohash-0.11.6
- curl-1.3.8
- data-binary-ieee754-0.4.4
- hashable-1.2.3.3
- hashtables-1.2.0.2
- hedis-0.6.9
- http-types-0.8.6
- lifted-base-0.2.3.6
- monad-control-1.0.0.4
- mongoDB-2.0.5
- mtl-2.2.1
- network-2.6.2.1
- parsec-3.1.9
- primitive-0.6
- random-1.1
- random-shuffle-0.0.4
- resource-pool-0.2.3.2
- scientific-0.3.3.8
- stm-2.4.4
- text-1.2.1.1
- transformers-0.4.3.0
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- utf8-string-1
- vector-0.11.0.0
